on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before adding'
        run: ls

      -  uses: actions/checkout@v3

      - name: 'after adding'
        run: ls  
